GitHubActionsTestLogger -> TUnit native

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,15 +27,13 @@ jobs:
     - name: Build
       run: dotnet build -c Release /p:ContinuousIntegrationBuild=true
 
-    # Remove the html head with the logo from README for nupkg
-    - name: Clean README
-      run: |
-        # Assert the pattern exists (Fail hard if not found)
-        grep -q "^# ArpLookup" README.md || { echo "Error: Header not found in README"; exit 1; }
-        # -n: don't print lines by default
-        # /pattern/,$p: print from the matching line to the end ($)
-        sed -n '/# ArpLookup/,$p' README.md > README.tmp
-        mv README.tmp README.md
+    # https://tunit.dev/docs/guides/html-report/#enabling-automatic-artifact-upload
+    - name: Expose GitHub Actions Runtime
+      uses: actions/github-script@v8
+      with:
+        script: |
+          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN']);
+          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL']);
 
     - name: Test
       # --no-build leads to empty coverage
@@ -45,6 +43,16 @@ jobs:
       uses: codecov/codecov-action@v5
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
+
+    # Remove the html head with the logo from README for nupkg
+    - name: Clean README
+      run: |
+        # Assert the pattern exists (Fail hard if not found)
+        grep -q "^# ArpLookup" README.md || { echo "Error: Header not found in README"; exit 1; }
+        # -n: don't print lines by default
+        # /pattern/,$p: print from the matching line to the end ($)
+        sed -n '/# ArpLookup/,$p' README.md > README.tmp
+        mv README.tmp README.md
 
     - name: Pack
       run: dotnet pack -c Release --no-build
